version: '3.8'

services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: i2i_oracle_db
    environment:
      - ORACLE_PASSWORD=i2iIntern2026
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: