CREATE TABLE MONTHLY_STATS (
    STAT_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    MONTH_NAME VARCHAR2(20),
    USED_DATA_GB NUMBER,
    USED_MIN NUMBER,
    USED_SMS NUMBER,
    PAYMENT_STATUS VARCHAR2(20),
    CONSTRAINT fk_stats_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);
CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER PRIMARY KEY,
    TARIFF_NAME VARCHAR2(100) NOT NULL,
    DATA_LIMIT_GB NUMBER,
    MIN_LIMIT NUMBER,
    SMS_LIMIT NUMBER,
    PRICE NUMBER
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(150) NOT NULL,
    CITY VARCHAR2(100),
    SIGNUP_DATE DATE,
    TARIFF_ID NUMBER,
    CONSTRAINT fk_customer_tariff FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);




CREATE INDEX idx_customers_city ON CUSTOMERS(CITY);
CREATE INDEX idx_monthly_payment ON MONTHLY_STATS(PAYMENT_STATUS);